project:
  type: website

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kennedymwavu
      - icon: twitter
        href: https://twitter.com/kennedymwavu
format:
  html:
    theme: default
    css: styles.css



