project:
  type: website
  output-dir: docs
  resources:
    - CNAME
website:
  title: "Mwavu's Blog"
  site-url: https://mwavu.com/blog/
  description: "Kennedy Mwavu"
  favicon: me-colored.jpeg
  page-footer: |
    ----
    blog by [kennedy mwavu](https://github.com/kennedymwavu)
    ----
  navbar:
    title: Home
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kennedymwavu
      - icon: twitter
        href: https://twitter.com/kennedymwavu
  back-to-top-navigation: false
  twitter-card: true
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    smooth-scroll: true
filters:
  - auto-dark
